/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>

#include "lexer.h"

int main () {
  xiangyuliu::parser::Lexer("");
  std::cout << "hello world" << std::endl;
  return 0;
}
